obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.1, 0.3], [0.9, 0.3],[0.9, -0.3], [-0.1,-0.3]] #[[-0.5, 0.3], [0.5, 0.3],[0.5, -0.3], [-0.5,-0.3]] FOR BASE_FLOOR
#robot_radius: ir_of_robot
inflation_radius: 0.6

observation_sources: laser_scan_sensor #point_cloud_sensor  

laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true}

# point_cloud_sensor: {sensor_frame: camera_depth_frame, data_type: PointCloud, topic: camera/depth/color/points, marking: true, clearing: true}