local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint #base_floor
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  transform_tolerance: 1.0
  plugins:
    # - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
    - {name: sonar_layer,             type: "range_sensor_layer::RangeSensorLayer"}
